### ISSUE TITLE
Show over dialog?

### ISSUE THREAD

**Issue by Nemi5150** [JohnPersano/SuperToasts#36]
SuperActivityToast works awesome, but I want to use it from an open dialog and it shows behind the dialog. Can you change it to show above all dialogs?

Alternatively, if you could put the LinearLayout for the SuperCardToast in any views layout instead of just the main layout, this would work as well.

**Comment by JohnPersano** [comment]
Nemi5150,

Unfortunately, this does not appear possible without adding some sort of System Alert permission to the library which would have to be included in every app using the library. This is especially unfortunate because the SuperActivityToasts with a button do not appear over the keyboard. Hopefully the API will change over time to accommodate this.

Thanks for the suggestion,

John
