### ISSUE TITLE
Configure Interpolator

### ISSUE THREAD

**Issue by Drakot** [JohnPersano/SuperToasts#64]
How about choosing the animation interpolator? Like bouncing, fading, coming from left to right or the other way around?

**Comment by JohnPersano** [comment]
Drakot,

Thanks for the suggestion. Unfortunately, this is not possible with SuperToasts since they use a WindowManager to add the toast View. This may be possible with SuperActivityToasts although I will have to create integer constants per each Interpolator since I don't believe Interpolators extend Serializable or Parcelable for orientation change recreation. Once I finish the current version of the library I'll add support for these.

Thanks for the idea!

John

**Comment by Drakot** [comment]
I was thinking about supercardtoast. I have seen the code ant it should be quite easy to parameterize.  

Thank you for your quick k response!

**Comment by JohnPersano** [comment]
Drakot,

I was not able to add this in version 2.0 of the library. I opened enhancement #86 that I hope to get to eventually. 

Thanks,
John
