### ISSUE TITLE
If I can set an id to a toast and update the toast with the id later.

### ISSUE THREAD

**Issue by maomaobug** [JohnPersano/SuperToasts#68]

**Comment by JohnPersano** [comment]
maomaobug,

Thanks for the input. Since SuperToasts are not meant to become a permanent member of any ViewGroup, I don't think this is appropriate. I assume it could be done by using a container for a SuperActivityToast and then grabbing the first child of that container but I can't imagine a need for that. SuperToasts, on the other hand, can't have an ID at all since they are added to the WindowManager. If you have a specific usage case in mind, please feel free to open another issue as an enhancement request and detail what you would like to see in a future update.

Thanks,
John Persano
