### ISSUE TITLE
Is the repository dead?

### ISSUE THREAD

**Issue by PanosSakkos** [JohnPersano/SuperToasts#83]
Hey,

Thanks for sharing!
I'm just curious if the repository is still maintained.
If not, it would be great to know it in order to switch to another toast framework.

Cheers!
:panos

**Comment by DavidEdwards** [comment]
Unfortunately, it seems like this repository is no-longer maintained.

For longer term safety I will move to a modern framework. @PanosSakkos have you located a good replacement?

**Comment by PanosSakkos** [comment]
@DavidEdwards unfortunately no. I just [hacked](https://github.com/dono-app/android/blob/master/src/app/src/main/java/com/dono/psakkos/dono/DonoToastFactory.java) the Toast in order to change the background color, but at the end of the day it's a crappy android toas with just a better color :sweat_smile:

**Comment by JohnPersano** [comment]
Hey guys.

Unfortunately, I have had little to no time to work on my Android projects for some time now. It's especially disappointing since I do have a mostly-functional version 2 sitting on my flash drive at home. In addition, I didn't think people were still interested in SuperToasts since Google came out with the official SnackBar repo. That being said, I will make every reasonable attempt this weekend to upload version 2 into a development branch. I might have to leave a few of the planned features out of the mix but the new version is significantly more mature in terms of code quality and API. If anyone is interested in helping test I would certainly appreciate it.

Thanks,

John

**Comment by JohnPersano** [comment]
@PanosSakkos @DavidEdwards SuperToasts has been updated to version 2.0. Thank you both for your continued support and patience.
- John

**Comment by PanosSakkos** [comment]
Thanks a lot for the effort @JohnPersano !  I will try out your new version! 😄

**Comment by ericntd** [comment]
@JohnPersano thanks a lot for your library
it's perfect for display a better - Toast message for purposes such as error/ success messages

Snackbar only shows at the bottom of the screen which doesn't get enough attention
